# Generated by Django 5.0.3 on 2024-07-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='responses',
        ),
        migrations.RemoveField(
            model_name='author',
            name='responses',
        ),
        migrations.AlterField(
            model_name='publication',
            name='name',
            field=models.CharField(max_length=68),
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
