# Generated by Django 5.0.3 on 2024-07-08 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_publication_responses_remove_author_responses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='author',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='app.author'),
            preserve_default='True',
        ),
    ]
