# Generated by Django 5.0.3 on 2024-08-24 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_publication_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='text',
            new_name='title',
        ),
    ]
