# Generated by Django 5.0.3 on 2024-08-23 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
