# Generated by Django 5.0.3 on 2024-07-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
