# Generated by Django 5.0.3 on 2024-08-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_text_publication_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.CharField(choices=[('pending', 'Отправлено'), ('accepted', 'Принято')], default='pending', max_length=20),
        ),
    ]
