# Generated by Django 5.0.3 on 2024-07-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_publication_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.BooleanField(verbose_name=(('AP', 'Обращение'), ('CP', 'Жалоба'))),
        ),
    ]
