# Generated by Django 5.0.3 on 2024-07-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_publication_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='upload',
        ),
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
