# Generated by Django 5.0.3 on 2024-08-23 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
