# Generated by Django 5.0.3 on 2024-08-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_response_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.CharField(choices=[('pending', 'отправлено'), ('accepted', 'принято')], default='отправлено', max_length=20),
        ),
    ]
