# Generated by Django 5.0.3 on 2024-07-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_publication_upload_alter_publication_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={},
        ),
        migrations.AlterModelOptions(
            name='response',
            options={'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.AddField(
            model_name='publication',
            name='responses',
            field=models.SmallIntegerField(default=0),
        ),
    ]
