# Generated by Django 5.0.3 on 2024-07-17 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_publication_options_alter_response_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='responses',
        ),
    ]
