# Generated by Django 5.0.3 on 2024-07-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_category_name_alter_publication_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.BooleanField(verbose_name=(('AP', 'Обращение'), ('CP', 'Жалоба'))),
        ),
    ]
