# Generated by Django 5.0.3 on 2024-07-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_publication_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Без категории', max_length=100),
        ),
    ]
