# Generated by Django 5.0.3 on 2024-07-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.BooleanField(default=True, verbose_name=(('AP', 'Обращение'), ('CP', 'Жалоба'))),
        ),
    ]
