# Generated by Django 5.0.3 on 2024-09-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_publication_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.CharField(choices=[('pending', 'отправлено'), ('deleted', 'удалено'), ('accepted', 'принято')], default='pending', max_length=20),
        ),
    ]
