# Generated by Django 5.0.3 on 2024-09-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_response_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.CharField(choices=[('pending', 'отправлено'), ('deleted', 'отклонено'), ('accepted', 'принято')], default='pending', max_length=20),
        ),
    ]
