# Generated by Django 5.0.3 on 2024-09-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_user_options_remove_publication_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='wrapper',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
